### ISSUE TITLE
DeviantArt Ripper not working anymore

### ISSUE THREAD

**Issue by ph0enixph0enix** [4pr0n/ripme#487] opened 2017-03-22 13:44 UTC
The big nasty bug:
DeviantArt updated their design some time ago - therefor the DeviantArt ripper does not find any images anymore.

Small bug: the login also does not work (fixable easily by exchanging url to get token / change select parameters).

**Comment by metaprime** [comment] 2017-03-23 08:41
Duplicate of https://github.com/4pr0n/ripme/issues/425

**Closed by metaprime** 2017-03-23 08:41 UTC
Labels: duplicate
