### ISSUE TITLE
No timeout on imgur/Removed

### ISSUE THREAD

**Issue by notacompletemoron** [4pr0n/ripme#217] opened 2015-05-27 02:51 UTC
It's tripping on forwards to http://i.imgur.com/removed.png

I'm using 1.1.8.

It's frustrating, as it's not dumping the subreddit into the history due to this. I have to close and manually go to the next in the queue, by manually typing it in.

**Comment by metaprime** [comment] 2016-12-21 14:08
I think I understand the issue, but it would be helpful if you could provide an example of a place where this happens, or confirm that the issue is fixed in the current version? https://github.com/4pr0n/ripme/releases

**Comment by notacompletemoron** [comment] 2016-12-23 04:04
Oh, yeah. It's definitely been fixed with a much earlier version. My apologies for not updating before hand.

**Comment by metaprime** [comment] 2016-12-23 08:56
@notacompletemoron Thanks for confirming this. Closing as Fixed!

**Closed by metaprime** 2016-12-23 08:56 UTC
Labels: bug, fixed, needs examples
