### ISSUE TITLE
Suggestion: Dropbox Support

### ISSUE THREAD

**Issue by tehloxely** [4pr0n/ripme#507] opened 2017-04-24 20:32 UTC
I would love to see Dropbox support for this app.

**Comment by cyian-1756** [comment] 2017-04-24 20:48
I don't really think that dropbox support is something that ripme should do. There are already well made programs to download from filelockers and trying to recreate that work in ripme would just make the program heavier and more bloated then it needs to be.

**Comment by metaprime** [comment] 2017-04-25 07:30
Duplicate of https://github.com/4pr0n/ripme/issues/285

**Closed by metaprime** 2017-04-25 07:30 UTC
