### ISSUE TITLE
Instagram won't download.

### ISSUE THREAD

**Issue by homardg** [4pr0n/ripme#330] opened 2016-05-31 23:38 UTC
Hello, it says "unable to find UserID at Iconosqaure." It was fine a day ago. I imagine that this was similar to the issue last year where Iconosquare updated their website.

**Comment by 0834dfbd2b** [comment] 2016-06-01 13:38
Yes it is similar abd this time it will proberly not change back.
There will be need for a whole new instagram plugin.

**Comment by domonic46** [comment] 2016-06-05 17:12
Request for a different plugin site: http://www.instagy.com
Example: instagy.com/user/yoventura

**Comment by chorijan** [comment] 2016-06-06 08:55
i think this isn't working anymore because Iconosquare changed and the Instagram API.

**Comment by saero** [comment] 2016-06-15 00:30
Hopefully the author can fix this soon, instagram is a key reason why I use RipMe. (Can anyone suggest maybe alternatives in the mean time?)

Also, does the author of RipMe have a donation page?

**Comment by 0834dfbd2b** [comment] 2016-06-17 22:30
Untill it get fixed you can use [Download FB Album mod for Chrome](https://chrome.google.com/webstore/detail/download-fb-album-mod/cgjnhhjpfcdhbhlcmmjppicjmgfkppok?utm_source=chrome-app-launcher-info-dialog)

**Comment by JoshKastang** [comment] 2016-06-24 22:15
Submitted PR #336 which should address the Instagram API changes.

**Comment by saero** [comment] 2016-06-30 22:31
Dear god I hope this gets updated soon. I hate switching applications, especially if they overwrite (without checking the file exists) or creates their own silly filenames rather than the original filename. I just need to update a few Facebook album dumps, oh well.

**Comment by saero** [comment] 2016-07-11 03:37
Besides 083's suggestion, what else can rip Instagram like RipMe used to do?

I don't use Chrome.

**Comment by autoborg** [comment] 2016-07-14 19:46
@saero I actually wrote a hacky Insta-ripper with Python. It's not great, as the better version was accidentally permanently deleted, but it should work alright.

https://github.com/autoborg/pyripper2

**Comment by user55** [comment] 2016-07-25 12:38
@autoborg 
Do you need to compile it or what? Can you add link to an executable file?

**Comment by saero** [comment] 2016-07-27 03:56
Im assuming RipMe is now defunct/the author does not care anymore, it's been 3 months and there's no way I'm going to get the functionality back (original filenames of the instagrams in to a specified folder of my choosing).

Thanks autoborg for the suggestion but I don't know how to use or code for python, I'm unfamiliar with that language.

**Comment by thedead** [comment] 2016-08-09 14:48
I think I made a fix- not sure how to upload it?  It works for me but maybe someone else could test

**Comment by JoshKastang** [comment] 2016-08-09 14:51
See PR #336. I've fixed this over a month ago. It hasn't been merged to master yet.

**Comment by autoborg** [comment] 2016-08-10 21:35
@user55 @saero Running Python scripts isn't particularly difficult. I'm happy to give you some simple instructions, and it shouldn't take more than a few minutes to set up. There's no compiling needed, just installing Python and one required module.

**Comment by clb92** [comment] 2016-08-10 22:39
I can confirm that @JoshKastang 's fix seems to work perfectly. I just downloaded the source files of Ripme, copy-pasted over the code from his commit, installed Maven and JDK, double-clicked a batch file and got a fixed version of Ripme. Not that hard at all! Still wish his fix would be merged soon though.

**Comment by Hrxn** [comment] 2016-08-11 11:58
Didn't Instagram changed their site code recently? You sure about getting the highest resolution possible?

**Comment by clb92** [comment] 2016-08-11 12:05
I just checked a random image downloaded by the fixed version, and it was 1080x1040px, and it's also 1080x1040px on the Instagram website. Not sure if it's possible to get higher resolutions.

**Comment by Hrxn** [comment] 2016-08-13 11:18
Yikes, the Instagram HTML source is a mess..

They don't seem to have a set of fixed image dimensions, which is actually good, but I tested some random Instagram pages and none had 1080x1040 px, they all varied around slightly lower values. What you see on the web site is actually a slightly scaled down image already.

I just took a quick glance at the source of #336 (Java fix) and [pyripper2](https://github.com/autoborg/pyripper2), and they work a bit differently to get their results.



pyripper2 gets the document source and retrieves a specific URL, does some string processing (cutting out crap), and et voilà!
_BTW, does it work with Python 2.x? Can't test right now, trip abroad._

#336 makes use of appending `/media/` to the user URL, which gets the information containing the stuff you see on an Instagram page in JSON format, then also does some string replacements and proceeds with the download afterwards.

_BTW, I think [this](https://github.com/JoshKastang/ripme/blob/c51dc1f80d7ae77335a779c47f20f504ff5a0375/src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java#L129) replacement doesn't work anymore, because the representation of the host in the URL has changed._

Now the thing is that what should be the image ID part of the URL actually differs between these two variants. Really great..

I suggest we agree on a good test case (IG user, as well as some single pages maybe), which will eventually allow to make sense of this mess..
Does anyone know an Instagram account with good quality images as an example? Because the majority seem to have a pretty awful image quality, to be honest.

**Comment by autoborg** [comment] 2016-08-17 23:03
@Hrxn While I haven't personally tested it, I'm almost certain that pyripper2 doesn't work with Python 2.x. The update from 2.7 to 3.x introduced a number of functions being renamed, and I know of at least one that is used in the script.

**Comment by saero** [comment] 2016-09-02 04:22
Good news everyone: If you use JDownloader2, they added an option to "Use original server filenames" for Instagram!

Now you can download an entire instagram or add to your existing rip of an instagram account using JD2!

I've swapped to JD2 since A) It appears RipMe won't be updated anymore except for kind souls who are forking it (bless you Josh Krang for having a fixed ripme for instagram 2 weeks ago!) and B) JDownloader2 is more heavily updated/constantly open to feedback on their forums.

https://board.jdownloader.org/showthread.php?t=70582

Check it out! I've made the swap, and also, unlike RipMe and its respective forks, JD2 downloads the CROPPED versions of images, rather than the 1080x1080 versions of images that have excess whitespace borders like RipMe does!

**Comment by sleaze** [comment] 2016-10-07 17:46
My goal isn't to be confrontational in any way, so this is purely informational and intended in the most friendly and helpful way:

Most importantly:

**Some of the forks here on github actually have implementations of features requested @ jdownloader "donate" screen's 'purpose of donating' bar.**

Less important but still noteworthy:

**JDownloader doesn't seem better.  The installer had a full screen, clearly crafted with love, dedicated to "donation" payments, accepting a whole tileset of payment methods.  This application screen then guilts you if you select "yes I'd like to donate" by throwing up an alert box stating "Are you really going to donate to JDownloader?".**

**The donation screen is also full of ads-talk or keep it ads free by donating.  Very promotional.**

**Comment by metaprime** [comment] 2016-12-19 11:51
I'm going to merge in a fix for this. Looking for the original patch.

**Comment by metaprime** [comment] 2016-12-19 12:03
Merged #336. Closing this issue. Please open a new issue if there are additional issues after the fix.

**Closed by metaprime** 2016-12-19 12:03 UTC
