### ISSUE TITLE
Rip multiply images from tweet

### ISSUE THREAD

**Issue by Norithiel** [4pr0n/ripme#500] opened 2017-04-01 10:38 UTC
Hello! Ripme only saves one pic from tweet with multiple images. Is there any solution for this bug?

**Comment by IT6uru** [comment] 2017-04-01 11:01
https://github.com/4pr0n/ripme/pull/478

**Comment by metaprime** [comment] 2017-04-06 02:31
@Norithiel Looks like a duplicate of https://github.com/4pr0n/ripme/issues/182
@IT6uru Thanks for linking to the PR.

**Comment by metaprime** [comment] 2017-04-06 02:32
Closing as duplicate.

**Closed by metaprime** 2017-04-06 02:32 UTC
Labels: bug, confirmed, duplicate
