### ISSUE TITLE
4chan not ripping on 12-19-16

### ISSUE THREAD

**Issue by Diskburner** [4pr0n/ripme#375] opened 2016-12-19 20:56 UTC
4chan not ripping on 12-19-16 , anyone else?

**Comment by metaprime** [comment] 2016-12-20 01:33
For now, assuming this is a duplicate of #362.

Please reply with a URL which demonstrates the problem and more info about what is happening and what you expect to happen. Thanks!

**Comment by metaprime** [comment] 2016-12-20 03:46
Confirmed this is the same issue. Closing as duplicate.

**Closed by metaprime** 2016-12-20 03:46 UTC
Labels: bug, confirmed, duplicate, needs examples, website changed

**Comment by metaprime** [comment] 2016-12-20 03:53
Fixed in 034f7ee1811eb7da7a96015d8a5390c79a876d64
