### ISSUE TITLE
Instagram and Private Accounts

### ISSUE THREAD

**Issue by tehloxely** [4pr0n/ripme#392] opened 2016-12-21 13:30 UTC
I'm sure you might know this already. But RipMe cannot download from private Instagram accounts. Would it be possible in the future to add your Instagram account to RipMe to be able to rip those accounts, that you're friends with, that are private? I currently am using 4k Stogram to do this, but that program is crazy heavy on RAM.

**Comment by metaprime** [comment] 2016-12-21 13:38
Duplicate of #125. I'll add my $0.02 there.

**Closed by metaprime** 2016-12-21 13:38 UTC
Labels: duplicate, enhancement
