### ISSUE TITLE
Issue: DeviantART 504 error

### ISSUE THREAD

**Issue by UnforeseenOcean** [4pr0n/ripme#325] opened 2016-04-25 12:31 UTC
While downloading from DeviantART, it spews out 504 error on 89% of files it found.
Here's an example of the error:
`
http://www.deviantart.com/download/127366525/indutrial_stock_3_by_bakanekonei.jpg?token=6693e1fa77e9e7aba9e2cd90e0724c07ec729795&ts=1461584723 : Retriable status code 504 while downloading http://www.deviantart.com/download/127366525/indutrial_stock_3_by_bakanekonei.jpg?token=6693e1fa77e9e7aba9e2cd90e0724c07ec729795&ts=1461584723`

I also tried setting the timeout to something like 1,000,000ms but it did little to no effect.
Plus, the download speed is now crawling. :(

**Comment by utopianduck** [comment] 2016-04-28 08:34
Been having similar issues, but with both 504 and 404 errors. Changing timeout speed having no real effect either

**Comment by metaprime** [comment] 2016-12-19 12:43
Duplicate of #337

**Closed by metaprime** 2016-12-19 12:43 UTC
Labels: bug, duplicate
