### ISSUE TITLE
Custom Tumblr API key not working

### ISSUE THREAD

**Issue by Ripperonii** [4pr0n/ripme#416] opened 2017-01-02 20:22 UTC
Hi so i recently got a new built so i had to re set up the program again and for the first time ever i started getting this message

>  "401 Unauthorized. Will retry with default Tumblr API key: JFNLu3CbINQjRdUvZibXW9VpSEVYYtiPJ86o8YmvgLZIoKyuNX" 

what does this mean? i registered my own key and have been using that one previously, i also tried registering a new one but it keeps giving me that error

**Comment by rautamiekka** [comment] 2017-01-02 21:12
If you try your own key with other ways than RipMe, does it consistently get shot back as unauthed ? Without asking Google Tumblr might somehow tell you if the API key is banned.

Did the default key work though ? If it did, then you might have a ban on your key.

**Comment by Ripperonii** [comment] 2017-01-02 21:15
how can i try my own key in another way?
hmm i tried making a new one and it gives me the same error and the last time i used my old one on my old pc it was working fine. And the default key worked

**Comment by rautamiekka** [comment] 2017-01-02 22:51
I've no idea about other ways, but googling should tell.

**Comment by metaprime** [comment] 2017-01-03 01:50
Duplicate of #415.

Apparently lots of traffic on the default API key since the revival of this project is causing this problem. Users will need to create their own API key to use to avoid this problem. Please replace the default API key in your `rip.properties` file.

**Comment by metaprime** [comment] 2017-01-03 01:52
My mistake, not a duplicate. This is telling you that your previous API key, or possibly that the API key from a previous version of RipMe (which has expired) is "401 Unauthorized" and it is trying the new API key -- if that works it will automatically update your settings for you.

Still recommend using your own API key if you can.

**Comment by Ripperonii** [comment] 2017-01-03 02:31
i did make a new one but it still gives me the same message so i don't know what to do

**Comment by metaprime** [comment] 2017-01-03 07:24
@Ripperonii the logic there was to update from the old default API key to the new one, or to fall back on the default key if the key in use doesn't work. I know that doing it that way makes it annoying to put in a custom key, but I couldn't come up with another "foolproof" way of forcing the update to the new key from people who had a previous version of Ripme and were using the expired one.

Not sure why you're having an issue though. I'll look into it.

**Comment by metaprime** [comment] 2017-01-03 07:26
@jgibson02 Could you share the steps you used to create the new Tumblr API key so users could reproduce your steps and get a working key of their own?

**Comment by jgibson02** [comment] 2017-01-03 07:47
https://www.tumblr.com/oauth/apps
Register a new application, just fill out the required fields, and copy the Consumer Key into TumblrRipper.java and rip.properties

**Comment by Ripperonii** [comment] 2017-01-03 14:16
ah, i didn't put it in the tumblrripper.java file, that must be it. what line am i supposed to put it in? @jgibson02

**Comment by Ripperonii** [comment] 2017-01-03 14:39
Downloading http://api.tumblr.com/v2/blog/(xxx,edited the name).tumblr.com/posts/photo?api_key=JFNLu3CbINQjRdUvZibXW9VpSEVYYtiPJ86o8YmvgLZIoKyuNX&offset=0&tag=me
Rip complete, saved to C:\Users\xxxi\Desktop\rips\tumblr_(xxx).tumblr.com_tag_me
null

this is what i get after putting even a new consumer oauth key in rip.properties

**Comment by jgibson02** [comment] 2017-01-03 16:44
What was the URL you entered into ripme?

**Comment by metaprime** [comment] 2017-01-05 18:41
@Ripperonii It's easier if you post the actual links without editing them so we can test. Just give a disclaimer that your link is NSFW.

**Comment by metaprime** [comment] 2017-01-06 17:00
@Ripperonii you don't need to modify the source code to get a custom Tumblr API key to work (if you did, that would be a bug we need to fix). The `rip.properties` change should be enough.

**Comment by lutewhack** [comment] 2017-10-17 16:56
When I insert my custom API key in rip.properties and then restart the .jar, it'll still default to the default API key. No matter what I do, it always reverts to the default and never uses my custom key.

**Comment by cyian-1756** [comment] 2017-10-17 17:59
@lutewhack This is the old repo (For a now very outdated version of ripme) please submit an issue to https://github.com/RipMeApp/ripme

**Comment by metaprime** [comment] 2017-11-21 11:27
@ghost Not clear whether any issue remains here. I'll close this issue. If you still have problems/concerns please open a new issue at https://github.com/RipMeApp/ripme

**Closed by metaprime** 2017-11-21 11:27 UTC
Labels: client issue
