### ISSUE TITLE
Issue with downloading from Reddit user profiles

### ISSUE THREAD

**Issue by MelonMusk** [4pr0n/ripme#316] opened 2016-04-05 02:34 UTC
I like to paste the Reddit user's profile link in ripme and it used to work like a charm, downloading every single album/photo submitted by the user. Lately it has been downloading some images only.

Example: The below user has two pages worth of Imgur albums but when I paste the link in ripme, only 12 images are downloaded.

https://www.reddit.com/user/loranna

Is this a known issue?

Cheers and long live ripme!

**Comment by sukhois** [comment] 2016-04-09 07:04
I can confirm this happening too with https://www.reddit.com/user/firefire85 

ripme it's getting only 9 images, and while she doesn't have many more, there are at least 3 more in her profile

**Comment by 4pr0n** [comment] 2016-04-17 02:36
Looks like the `imgur.com/gallery/...` links weren't working due to a change in imgur's page metadata.

Should be fixed in 1.2.10

**Closed** 2016-04-17 02:35 UTC
