### ISSUE TITLE
ripme will not maximize

### ISSUE THREAD

**Issue by evc1234** [4pr0n/ripme#263] opened 2015-11-04 07:31 UTC
Hello,

First of all thank you for the program! Second of all, it appears that ripme does not want to maximize? I can open it and it will show in my taskbar, I can open the aboutme etc but when it is fully maximized it is the tiniest size possible and the maximize button is greyed out and unable to be used.

I am on windows 7.

Any ideas? Thanks.

**Comment by evc1234** [comment] 2015-11-04 07:36
I should add that this is on a completely fresh install.

**Comment by wpw** [comment] 2015-11-27 21:34
Things to try:
1) Make sure you run the program from it's location directly. No shortcuts, search results windows, etc.
2) Delete the history and properties files. Back them up first just in case.

**Comment by i-cant-git** [comment] 2016-01-09 04:11
Ripme should allow to maximize, History page is so small, I can't even see the URLs.

**Comment by metaprime** [comment] 2016-12-19 12:31
Duplicate of #306

**Closed by metaprime** 2016-12-19 12:31 UTC
Labels: bug, enhancement

**Comment by metaprime** [comment] 2016-12-21 14:53
#371
