### ISSUE TITLE
Bug: Making the properties, history, and possibly the log files hidden makes them innaccessible to RipMe

### ISSUE THREAD

**Issue by Skyleaf** [4pr0n/ripme#229] opened 2015-06-26 03:13 UTC
I just recently figured this one out. It seems like if you make **history.json**, **rip.properties**, and possibly **ripme.txt** hidden in Windows, RipMe cannot access the files. While it will still read the settings saved in rip.properties, it cannot modify them. Any changes in settings you make while that file is set to hidden will be undone when the program is closed. History does not save when history.json is hidden. When you look at the logs, it will mention a file access error:

`java.io.FileNotFoundException: history.json (Access is denied)`

and

`2015-06-25 20:57:07,833 ERROR utils.Utils .saveConfig() Error while saving configuration: 
org.apache.commons.configuration.ConfigurationException: Unable to save to file C:\Users\Folder Path\rip.properties`

I'm pretty sure the log file doesn't update as well if it is hidden, but I haven't thoroughly tested that out.

**Comment by drguildo** [comment] 2015-06-28 13:02
It doesn't look like this is a problem with RipMe, it's a "feature" of Java on Windows; you simply don't seem to be able to write to hidden files.

The only potential solution is to set the file to unhidden, write to it, then set it hidden again. This seems very hacky and is probably not a good thing to do considering the user might have a reason to want the file set to hidden at all times.

**Comment by Skyleaf** [comment] 2015-06-28 14:26
Interesting. I'm somehow unsurprised, to be honest. Well, at least I know it isn't a bug in the software. I ended up just moving the files and software into a different folder where I wouldn't need to hide the extra files and then setup a shortcut to it. So it works out, better in the end actually, since I finally found out how to pin a shortcut to a Java program on the taskbar. I've made things much easier on myself. Thanks for letting me know! I guess this should be closed then, unless there is something that can be done about it?

**Comment by metaprime** [comment] 2016-12-22 11:52
Closing as wontfix

**Closed by metaprime** 2016-12-22 11:52 UTC
Labels: wontfix

**Comment by rautamiekka** [comment] 2016-12-23 02:18
Repeated
- unhide
- read and/or write
- hide

is unhealthy for SSD drives. If it can be avoided, avoid it.

**Comment by metaprime** [comment] 2016-12-23 08:46
I'd say the problem is just that these files shouldn't be made hidden in the first place. Whatever mechanism made them hidden -- well, don't do that.

Anyway I'm not sure the unhide/write/hide problem is really a problem for SSDs or any hard drive.

SSD drivers are smart, and good at avoiding writes when possible -- when a change to a file is saved (the file system is updated) it doesn't necessarily mean the file has been updated on the physical disk. It could still reside in RAM until a certain time passes where the changes are committed to disk. I'm not sure how journaling works with the specific limitations of SSD patterns, but there may be a journal updated with the changes instead of rewriting a file. Appending to the same sector in a journal is a good pattern for SSDs.

Reading data from the file is a basic requirement, nothing to fix there. Also if reads are "bad" for the SSD in the sense that it wears down the drive, then sure, but a read is a basic need and is definitely the LEAST bad for an SSD.

**Comment by rautamiekka** [comment] 2016-12-23 12:54
^ Delaying doesn't do shit for limited wearability and just being tougher doesn't prevent anything, even if writing was delayed, and not writing the data right away means increasingly bigger data loss. Writing for nothing is the problem HDDs don't suffer from.

**Comment by drguildo** [comment] 2016-12-23 16:10
Just disconnect it and it'll never wear out.

**Comment by rautamiekka** [comment] 2016-12-23 17:09
^ Can't believe someone actually said that -.-.

**Comment by metaprime** [comment] 2016-12-24 00:21
Trust the drivers to do the right thing. If there's no change after delaying updates (temporarily writing to RAM), then nothing changes on disk. This is a thing that literally actually happens today, and not something we have control over. Under "normal" workload, which includes this program and so many other things that your computer already does, SSDs can last a long time. Unless you're using your SSD in a server or data center scenario or writing and erasing huge amounts of data all the time, you have nothing to worry about.

Anyway I've already said I'm not going to add the pattern of changing the visibility of a file to fix this problem. Nothing more to worry about here.
