### ISSUE TITLE
ripme truncates trailing underscore in URL

### ISSUE THREAD

**Issue by cppsse** [4pr0n/ripme#579] opened 2017-06-13 16:29 UTC
When downloading a reddit user account, if the account has a trailing underscore in the username, ripme seems to truncate it.  For example:

user@host:/mnt/files$ java -jar /usr/local/bin/ripme.jar -l . -u https://www.reddit.com/user/cracking_
Loaded file:/usr/local/bin/ripme.jar!/rip.properties
Loaded log4j.properties
Initialized ripme v1.4.19
[+] Creating directory: ./reddit_user_cracking
...

**Comment by drewmilizia** [comment] 2017-06-15 00:54
I am pretty sure someone looked into it at some point, but not sure where its at now:

https://github.com/4pr0n/ripme/issues/435

**Comment by cppsse** [comment] 2017-06-15 04:43
Thank you.  I'm using ripme v1.4.19 on Debian Jessie.

**Comment by metaprime** [comment] 2017-06-18 06:47
Yep, closing as duplicate of #435

**Closed** 2017-06-18 06:47 UTC
Labels: duplicate
