### ISSUE TITLE
corrupt history file causes miniature/unresponsive window

### ISSUE THREAD

**Issue by patoflecloune** [4pr0n/ripme#166] opened 2015-02-06 21:23 UTC
I have a problem similar to [nameplate1]. After multiple rips (number varies) when I open RipMe it only opens a miniature window that I can't maximize and an icon in the task bar. When this happens I haven't found a way to use the program. The "clipboard autorip" command on the taskbar icon doesn't seem to work either.

When the history file is removed from the folder where the JAR is, it opens normally (usual window with settings, history, log and everything functionnal). This of course erases my history.

I now have 2 history.json files backed up elsewhere and no way to get the links in them back. The first one was huge so I thought this was the issue but the problem re-occured yesterday and it had max a couple dozen links in history.

In the options menu the only checked boxes I have are: Preserve order+Save album titles. I am running v1.1.4

Thanks for the program, I'm hoping this can be fixed.

**Comment by 4pr0n** [comment] 2015-02-08 07:32
Can you attach or paste the contents of the history files (the ones that cause the program to crash)? You could paste it on `pastebin` ...

**Comment by patoflecloune** [comment] 2015-02-08 07:40
Both notepad and word-pad give me only blank characters, no text. What do you use to open them?

**Comment by 4pr0n** [comment] 2015-02-08 07:43
Blank characters? Yikes. You could upload it to a file-sharing site. [rghost.net](http://rghost.net/) doesn't require any login; alternatively there's dropbox, mega, mediafire, etc...

In the mean time, I pushed 1.1.6 which catches when the history file can't be loaded, warns that the file will be overwritten, and then loads the program normally.

**Comment by patoflecloune** [comment] 2015-02-08 07:50
here's the most recent one. http://rghost.net/7FlXGHZYp

I'm now running 1.1.5 with the same issue, gonna update to 1.1.6

thanks

**Comment by 4pr0n** [comment] 2015-02-08 07:59
Looks like it wrote 17kb of `null` characters (`0x00`). Looks like there's no way to recover your previous history :(

This is where the code writes the `history.json` file: https://github.com/4pr0n/ripme/blob/master/src/main/java/com/rarchives/ripme/ui/History.java#L130-L138

I don't see any reason why that would output a bunch of null characters... I tried loading a huge history file (thousands of entries) but the program was able to load/save as usual...

**Comment by patoflecloune** [comment] 2015-02-08 08:05
I had already pretty much abandoned all hope, guess I'll delete those empty backups.

Would it be possible to re-establish a history with the rip folder? I mostly rip on reddit  so tons of my folders are reddit_user_[insert username]

**Comment by 4pr0n** [comment] 2015-02-08 08:08
That's actually a good idea; if there's no history, the program could "divine" your history based on the directory names in the `/rips/` directory.

This will require some work...

**Comment by patoflecloune** [comment] 2015-02-08 08:18
Sadly I can't help, I'm totally inept with code.

I'm already grateful for the tool you designed. However if you ever manage to implement this, it would be awesome.

**Comment by metaprime** [comment] 2016-12-20 19:42
I saw the case where entire files were overwritten with the same number of bytes of NUL 0x00 characters. I forget the cause but it was related to file system corruption. That was on Ubuntu running in a server cluster, and any number of things could have gone wrong there. It sounds like @patoflecloune's issue is on Windows. It might be similar or it might not.

In my case, so much of my work was damaged, the admins had to restore my entire user directory to a good backup from a week before. Still lost some work that way, but it was better than nothing. I was happy that all my code from the lost week was backed up on bitbucket for the project I was working on. College was good times...

**Comment by metaprime** [comment] 2016-12-20 19:44
In the meantime I think this issue can be repro'd by intentionally corrupting the history file.

Even if the file can't be saved, it's possible it's not corrupted beyond repair, maybe copy the existing file to a backup file before overwriting it?

**Comment by metaprime** [comment] 2016-12-22 12:12
I think it's safe to close this as a fluke client issue. Haven't seen any other complaints, but if they come up we can handle a new issue.

**Closed by metaprime** 2016-12-22 12:12 UTC
Labels: bug, client issue, UI
