### ISSUE TITLE
Tumblr rips report null

### ISSUE THREAD

**Issue by L3sb0t** [4pr0n/ripme#490] opened 2017-03-24 23:07 UTC
When I try to rip from Tumblr, I get a red message saying "null".

**Comment by cyian-1756** [comment] 2017-03-24 23:13
What url are you trying to rip and what version of ripme are you running?

**Comment by L3sb0t** [comment] 2017-03-25 02:38
The url is http://beeple.tumblr.com/ and I'm running the most recent ripper, 1.4.6 .

**Comment by cyian-1756** [comment] 2017-03-25 02:57
It's a too many requests error, you have to replace the tumblr api key (`tumblr.auth` in rip.properties) with your own tumblr api key.

You'll need to [register an application](https://www.tumblr.com/oauth/apps) to get an api key.

**Comment by cyian-1756** [comment] 2017-03-31 06:19
@L3sb0t Did replacing the api key solve this issue? If so can you please close this issue

**Closed** 2017-04-01 23:07 UTC

**Comment by amolad** [comment] 2017-04-02 01:52
>You'll need to register an application to get an api key.

HOW do you do that?

**Comment by cyian-1756** [comment] 2017-04-02 13:55
@amolad 

You need a Tumblr account

Go here: https://api.tumblr.com/console

Click Register a new application

Fill out all required fields, etc. Just enter something

**Comment by amolad** [comment] 2017-04-03 00:10
>You need a Tumblr account

>Go here: https://api.tumblr.com/console

>Click Register a new application

>Fill out all required fields, etc. Just enter something

I don't want a fucking tumblr account. 
Just forget it. JDownloader rips tumblr pages quite easily.

**Comment by metaprime** [comment] 2017-04-08 18:51
You just get a key and leave it. I'm not sure what the problem is here.

Someone want to look into how JDownloader manages to get around rate limiting without needing a key?

**Comment by Hrxn** [comment] 2017-04-09 12:14
Someone know an open source repo of JDownloader?

Not sure if that is really possible in Tumblr's case, though. You use the API, you need a key.
Perhaps they're doing it the "good" old way, retrieving HTML and then scraping it?

**Comment by rautamiekka** [comment] 2017-04-09 14:26
^ http://lmgtfy.com/?q=jdownloader+source+code

**Comment by Hrxn** [comment] 2017-04-09 15:45
Which one is it? Looks all like outdated crap?

**Comment by rautamiekka** [comment] 2017-04-09 17:36
The official doc said 'Subversion repo' and gave SVN address and ended up finding it at https://svn.jdownloader.org/projects/jd

Seems they were originally at GitHub, moved to OpenHub, then started hosting their own.

**Comment by droidberg** [comment] 2017-04-13 08:17
so is there any fix yet for tumblr that doesnt require all this bs? anyone know of any app that can rip tumblr pages?

**Comment by cyian-1756** [comment] 2017-04-13 21:16
@droidberg 

> so is there any fix yet for tumblr that doesnt require all this bs?

Tumblr works most of the time without needing a new api key
