### ISSUE TITLE
4chan still not fully ripping

### ISSUE THREAD

**Issue by LanceBoyle94** [4pr0n/ripme#426] opened 2017-01-14 08:23 UTC
So I saw that an issue was fixed not too long ago where 4chan albums wouldn't download all images, as some would be under a different name/domain (is.4chan.org). Well, as it turns out there's also another one, similarly named. It's is2.4chan.org. Why exactly have they done that, I dunno.

But yes, it's now missing those.

**Comment by cyian-1756** [comment] 2017-01-23 11:58
I fixed this issue in my fork, it should be in the main repo around February

**Comment by Hrxn** [comment] 2017-01-23 12:41
Another alternative, until the fix gets merged:
https://github.com/SuperGouge/ChanThreadWatch

Don't know if this new issues appears using that as well, if you give me a sample thread to test with - that exhibits this issue with a new domain -, I'll try it and report back.

**Comment by metaprime** [comment] 2017-02-01 01:23
Duplicate of #432

**Closed by metaprime** 2017-02-01 01:23 UTC
