### ISSUE TITLE
Imagefap downloads as txt

### ISSUE THREAD

**Issue by evaporatedwhiz** [4pr0n/ripme#517] opened 2017-04-26 12:06 UTC
can no longer download images, only downloads as one text file with the image names as text. affects new version as well

**Comment by cyian-1756** [comment] 2017-04-26 13:20
Can you post the url you're trying to rip?

**Comment by evaporatedwhiz** [comment] 2017-04-27 12:00
Here's one example http://www.imagefap.com/pictures/6819380/Betcee?gid=6819380&view=2 

it goes thru the motions then launches a text file with the filenames in it. i installed a new version but the results were the same

**Comment by cyian-1756** [comment] 2017-04-27 12:34
It works fine for me, do you have the "save urls only" option checked in ripmes settings?

**Comment by metaprime** [comment] 2017-05-09 18:09
Confirmed the ripper works for me.

You probably have this option selected:

![image](https://cloud.githubusercontent.com/assets/7526632/25865494/e745949c-34a7-11e7-9181-9061ecd051dc.png)

**Closed** 2017-05-09 18:10 UTC
Labels: can't repro, client issue
