### ISSUE TITLE
I cant get anything from 4ch either....

### ISSUE THREAD

**Issue by Diskburner** [4pr0n/ripme#440] opened 2017-02-04 17:24 UTC
I cant get anything from 4ch either. i dl'ed the latest master and jar. but still nothing. is there a fix on our end or do we need to configure to allow 4ch new image server??

**Comment by cyian-1756** [comment] 2017-02-04 18:49
> s there a fix on our end or do we need to configure to allow 4ch new image server??

The current buold (1.4.1) has a minor bug with 4chans sub domains, you can download my [build](https://github.com/cyian-1756/ripme/releases/download/1.4.1/ripme-1.4.1-jar-with-dependencies.jar) and it should rip 4chan without issue

**Comment by metaprime** [comment] 2017-02-09 10:10
Closing as duplicate of https://github.com/4pr0n/ripme/issues/432

**Closed by metaprime** 2017-02-09 10:10 UTC
Labels: duplicate
