### ISSUE TITLE
Tumblr has changed its API? 

### ISSUE THREAD

**Issue by seattle255** [4pr0n/ripme#339] opened 2016-07-27 20:26 UTC
It looks like Tumblr has changed or done something odd  to its API. Upon attempting to rip Tumblr sites I am now receiving this error: 

> Downloading http://api.tumblr.com/v2/blog/letmedothis.tumblr.com/posts/photo?api_key=v5kUqGQXUtmF7K0itri1DGtgTs0VQpbSEbh1jxYgj9d2Sq18F8&offset=0
> Rip complete, saved to /Users/Redburn2/Downloads/rips/tumblr_letmedothis.tumblr.com
> Failed to load http://api.tumblr.com/v2/blog/letmedothis.tumblr.com/posts/photo?api_key=offset=0 after 1 attempts

The error about failing to load the Tumblr API seems to recur. 

Letmedothis.tumblr.com is a reasonable test point. It has worked in the past.

**Comment by kingharold1st** [comment] 2016-07-28 12:59
Same problem here

**Comment by Hrxn** [comment] 2016-07-28 19:19
Nope, don't think so. API still looks the same.

Maybe try the steps mentioned there: https://github.com/4pr0n/ripme/issues/335

**Comment by kingharold1st** [comment] 2016-07-28 20:49
Yes, sorry for bothering.
i noticed some time later.

2016-07-28 21:19 GMT+02:00 H R X N <notifications@github.com>:

**Comment by Hrxn** [comment] 2016-07-28 20:51
No problem. :+1:

**Comment by kingharold1st** [comment] 2016-07-29 08:23
Hi, sorry to bother again but i have a question.
if you are to busy or not willing to help, i can understand.
just stop reading and tell me please.


I am not that familiar with java.
i am playing a little bit around with your source code since i experienced
some problems with the deviant art ripper.
i wanted to have the deviant art timeouts configurable.
now i have problems to generate a runnable jar file.
i get the following error messages:
log4j:WARN No appenders could be found for logger
(org.apache.commons.configuration.PropertiesConfiguration).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.
Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at
org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
at com.rarchives.ripme.utils.Utils.getConfigBoolean(Utils.java:104)
at com.rarchives.ripme.utils.Utils.configureLogger(Utils.java:350)
at com.rarchives.ripme.App.main(App.java:38)
... 5 more

greetings
Martin


2016-07-28 22:51 GMT+02:00 H R X N <notifications@github.com>:

**Comment by metaprime** [comment] 2016-12-19 12:08
Closing as duplicate of #335

**Closed by metaprime** 2016-12-19 12:08 UTC
Labels: discussion, duplicate
