### ISSUE TITLE
ImgurRipper title grabbing sometimes sliently fails

### ISSUE THREAD

**Issue by cyian-1756** [4pr0n/ripme#587] opened 2017-06-22 13:20 UTC
* Ripme version: 1.4.20
* Java version (output of `java -version`): openjdk version "1.8.0_131"
* Operating system: ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: http://imgur.com/a/9rX1v [NSFW]
* Please include any additional information about how to reproduce the problem: It only seems to occur when imgur is under high load

## Expected Behavior

Ripme gets the album title from the imgur page

## Actual Behavior

Ripme gets the string "Imgur: The most awesome images on the Internet" as the title

**Comment by cyian-1756** [comment] 2017-06-22 13:24
Looking over the source of http://imgur.com/a/9rX1v [NSFW] having the ripping fall back to the <title> tag if og:title returns "Imgur: The most awesome images on the Internet" might fix it

**Comment by metaprime** [comment] 2017-06-23 17:05
Duplicate of #509

**Closed** 2017-06-23 17:26 UTC

**Comment by metaprime** [comment] 2017-06-24 21:21
> Edit: Falling back to the <title> tag doesn't fix it.

Right, because the problem is the album doesn't have a title and the actual title of the page is the one imgur provides when there is no album title. We can detect this text and know from there that the album title should be left blank.

**Comment by cyian-1756** [comment] 2017-06-25 09:03
> Right, because the problem is the album doesn't have a title and the actual title of the page is the one imgur provides when there is no album title

Nope, I'm talking about when this happens with albums that are titled when imgur is under high load. Even tho the album has a title imgur doesn't display the title on the page

**Comment by metaprime** [comment] 2017-06-25 16:38
I've never seen that happen, but definitely something to take into account. Thanks for being thorough!
