### ISSUE TITLE
Imgur album page format changed, now only downloads first 10 images in an album

### ISSUE THREAD

**Issue by metaprime** [4pr0n/ripme#266] opened 2015-11-27 19:02 UTC
It seems they've hidden the rest of the album in a way that requires clicking on the show more link to load them into the page. I haven't been able to determine the location they are loading the json from and I don't think the framework ripme uses to load pages will support triggering click events and running the javascript to update the page.

Maybe we should consider switching to the imgur API.
https://api.imgur.com/oauth2
https://api.imgur.com/endpoints/gallery#album

Example: for this album
http://imgur.com/a/JTH78
The API URL will look like:
https://api.imgur.com/3/gallery/album/JTH78

But we need to get the API key and perhaps user's openauth so that the program can use the API.

**Comment by metaprime** [comment] 2015-11-28 00:54
I used the Network tab in chrome to see the source that is loaded when the link to get more is clicked.

For http://imgur.com/a/IRFA9
http://imgur.com/ajaxalbums/getimages/IRFA9/hit.json?all=true

Each line in the response json looks like this:
{"hash":"gFnzQE1","title":"","description":"","width":1050,"height":700,"size":145943,"ext":".jpg","animated":false,"prefer_video":false,"looping":false,"datetime":"2014-08-20 15:20:12"}

For each line of that we can reconstruct the imgur link easily:
http://i.imgur.com/gFnzQE1.jpg

To make it easy, we just need a JSON parser.

**Comment by FrootiousLoopious** [comment] 2015-12-13 08:20
I've found out how you can download all the images, you simply need to login with your imgur account and then put it in the ripper. It's an odd fix, but it works.

**Comment by Hrxn** [comment] 2015-12-13 14:45
Guys, serious question:

On both album pages linked here, when you scroll all the way down, you see the 'Post Options' button, as usual.

Click that button, select 'download album', and you will get a .zip archive with some image files inside.
Looks like all the images are there, or did you find some pictures missing? Or wrong resolution? Looks correct to me..

**Comment by FrootiousLoopious** [comment] 2015-12-17 09:16
@Hrxn No, the files are fine and normal res, it's just that sometimes imgur requires you to submit your email and wait for the link if the album is too big. A workaround to this however is simply adding s. in the front of imgur and .zip at the end of the link so for example, "s.imgur/a/testalbumname.zip"

**Comment by 4pr0n** [comment] 2015-12-19 14:28
The latest version (v1.2.0) seems to work for large imgur albums, e.g. https://imgur.com/a/lBQGv

That version's been out for a while... Is this still an issue?

**Comment by Hrxn** [comment] 2015-12-22 07:39
Okay, first of all, none of the API links here did work for me even when signed in with a Imgur account:

Here are three albums linked so far: JTH78, IRFA9, IBQGv

https://api.imgur.com/3/gallery/album/JTH78
https://api.imgur.com/3/gallery/album/IRFA9
https://api.imgur.com/3/gallery/album/IBQGv

I always get this:
`{"data":{"error":"Authentication required","request":"\/3\/gallery\/album\/JTH78","method":"GET"},"success":false,"status":401}`

Interestingly, with the URL from the second comment
> http://imgur.com/ajaxalbums/getimages/IRFA9/hit.json?all=true

I get different results, maybe test for yourself:

http://imgur.com/ajaxalbums/getimages/JTH78/hit.json?all=true
http://imgur.com/ajaxalbums/getimages/IRFA9/hit.json?all=true
http://imgur.com/ajaxalbums/getimages/IBQGv/hit.json?all=true

The third album, [IBQGv](https://imgur.com/a/lBQGv) only gives me this:
`{"data":[],"success":true,"status":200}`
Do you get the same result?

This album should have 331 Images, according to the album title:
> Killer and a Sweet Thang: 331 images

I did try a rip yesterday and I got 331 images, I think. I can't look into this right now, because I'm still on the road.

I noticed another interesting thing here, items number 61 and 62 are .gif animations.

If you copy the URL of the link (not the URL of the image itself, cause that is only a .jpeg thumbnail) you will get:

https://i.imgur.com/OZVG99O.gif
https://i.imgur.com/zvHjoCP.gif

But if you open these two items from within the album, you will land at these URLs:

https://imgur.com/a/lBQGv#60
https://imgur.com/a/lBQGv#61

Which don't work for me as direct links, but I guess this is intentional. But clicking on them opens the Imgur image viewer overlay, and in the upper right corner you have the 'actions' menu, if you select view full size you will get:

https://i.imgur.com/OZVG99O.gifv
https://i.imgur.com/zvHjoCP.gifv

These are .webm files, which have better quality than .gif and are *a lot* smaller..

Downloading in the 'action' menu will give you the big .gif files..

I can't check right now which files ended up in the directory, as I said, but I will check that later ;-)

**Comment by 4pr0n** [comment] 2015-12-22 15:14
The ripper prefers imgur's older API (which doesn't require OAuth authentication) but has fall-backs to other methods. Pretty sure the current version can rip any album without issue... still waiting for an example imgur URL that RipMe can't rip...

> These are .webm files, which have better quality than .gif and are a lot smaller..
I think imgur converts .gif to .webm and .mp4 as an alternative way to view GIFs, likely to save bandwidth & hosting costs since the file sizes are smaller. But just because it's webm doesn't mean it's higher quality; a .webm file generated from a .gif will have the same (or worse) quality than the .gif -- it can't have "better".

**Comment by Hrxn** [comment] 2015-12-23 00:11
First of all, at home and checked my rip dir of https://imgur.com/a/lBQGv.
I can confirm, this works, 331 images. On top I compared it with the content of the archive file that Imgur gives you, and they are exactly the same. I verified the checksums.

100/100 points

> But just because it's webm doesn't mean it's higher quality; a .webm file generated from a .gif will have the same (or worse) quality than the .gif -- it can't have "better".

This is obviously true, but I don't think that their processing pipeline creates the .webm from the .gif
Besides, please compare the links for yourself:

https://i.imgur.com/OZVG99O.gif
https://i.imgur.com/OZVG99O.gifv

and

https://i.imgur.com/zvHjoCP.gif
https://i.imgur.com/zvHjoCP.gifv

I see a difference in both examples. Subtle, but it's there.

And the size, of course, a random gallery with ~ animations is 25 MiB with .webm, while the .gif variant would be easily above 200 MiB.

Also, Imgur has this feature (http://imgur.com/vidgif), like some other sites, an automatic creation of animations from a video source. I haven't done it myself yet, but I think that's where they get the .webm from first..


Something different:

The link from my last comment:
http://imgur.com/ajaxalbums/getimages/lBQGv/hit.json?all=true

Suddenly works for me?! What is this? Anyone an idea?

**Comment by Hrxn** [comment] 2015-12-23 00:20
Holy mother of Christ...

![temp](https://cloud.githubusercontent.com/assets/12064918/11968982/4a94805c-a913-11e5-8cfd-e8db0649a86a.jpg)

Small 'l' vs big 'I'

Lesson: Less typing, more copy'n'pasting

**Comment by 4pr0n** [comment] 2015-12-23 04:52
Glad we figured that out. I think it's safe to close this issue since it looks like the imgur album ripper works again.

Feel free to create a new issue / enhancement request to favor to webm, mp4, or GIF when applicable.

**Comment by Hrxn** [comment] 2015-12-24 06:46
Yes, I think it can be closed..

For the record, as a feature request, I would like the possibility to get the webm or mp4 instead of the GIF format, but please consider this as low priority ;-)

**Closed** 2015-12-24 21:40 UTC

**Comment by metaprime** [comment] 2016-02-18 08:27
#284 and #300 are duplicates of this
