### ISSUE TITLE
It seems like de-duplication isn't great.

### ISSUE THREAD

**Issue by anonCoder123** [4pr0n/ripme#565] opened 2017-06-05 00:24 UTC
I have the overwrite files option unclicked, yet if I rip the same url multiple times I will end up with duplicate files.

The output from ripme application seems as if there is some de-duplication going on, since it will say blah.jpg already saved as blah.jpg, etc but I think it is not working properly.

I didn't notice it at first until my HD was almost full. I used Duplicate Cleaner, it finds duplicate files based on hashing, and found something like 500 GB of duplicate files in my rips folder.

I now run Duplicate Cleaner once or twice a month to clean up the duplicates, but it would be nice not to have to do this.

**Comment by Hrxn** [comment] 2017-06-05 09:12
Ripme doesn't do any real deduplication, by design.

**Comment by rautamiekka** [comment] 2017-06-06 13:17
Indeed, there's **zero deduping** in RipMe.

What that does is, unchecked, leave existing files alone.

**Comment by metaprime** [comment] 2017-07-13 10:07
Thanks for the report, but it looks like there's no action to take here.

Closing as Won't Fix / By Design

**Closed by metaprime** 2017-07-13 10:07 UTC
Labels: wontfix
