### ISSUE TITLE
deviantart ripping broken

### ISSUE THREAD

**Issue by onesimpleclik** [4pr0n/ripme#496] opened 2017-03-29 00:59 UTC
have been unable to rip albums or photos from deviantart for quite a while.

is there any word on a fix being found for this?

sample path: http://inkveil-matter.deviantart.com/gallery/?catpath=/

**Comment by cyian-1756** [comment] 2017-03-29 02:07
> is there any word on a fix being found for this?

There's been some talk in other issues about this but AFAIK no one has commit to fixing it

**Comment by rautamiekka** [comment] 2017-04-12 16:38
It's still very much needed cuz although JDownloader has been updated so numerous times within a couple months and does handle DA gallery and any explicitly named folders, but

1) it's not recursive
1.1) subfolders aren't picked up even in deep scan regardless of direct link to a folder with a subfolder
1.2) any folders right under gallery aren't picked up, have to explicitly link them
1.3) the 'full gallery' link like the one given by @onesimpleclik is unsupported
2) even when using deep scanning you don't get everything; one artist who just came back from deactivation has 1092 items uploaded (think it means journals and other stuff as well), but JD picked up 702 from all folder links I gave it, confirmed by using a calculator to sum up the numbers all manually, giving 41 items not downloaded; wonder what DA is counting as deviations if fully manual calculation gives a value that's not totally far from what the ripper gave. He doesn't have that many other things you can see that'd make up 1092 (favs aren't counted in it, it's a separate statistic of 8274 items), so JD's ripper is severely limited.

**Using JD only cuz it's the only somewhat working DA ripper.** RipMe has to be fixed. I've had a look at the rippers provided for RipMe and it's not rocket science, so I'll see how far my extremely poor Java goes ...

**Comment by Hrxn** [comment] 2017-04-13 11:24
Okay, let's take a close look.

Example from OP:
http://inkveil-matter.deviantart.com/gallery/?catpath=/
This is what you get when you go to *Gallery > All*, apparently.
http://inkveil-matter.deviantart.com/gallery/
That is the "normal" gallery.

It is obvious that both links do not display the same amount of gallery elements.
The way I see it, the "normal" gallery does not display the items that have been filed into a gallery folder, as seen on the left side of the page, whereas the link with `/?catpath=/ shows all of the elements from the "normal" gallery, *plus* the content from the gallery folders, all in one grid.

You can check by counting manually, or by using something like this `document.querySelectorAll("span.saved-faved-corner").length;` or `document.querySelectorAll("a.torpedo-thumb-link").length;` But you have to scroll to the end of the gallery grid first, because it's a dynamic page.

This got me:
http://inkveil-matter.deviantart.com/gallery/?catpath=/
155 elements.
http://inkveil-matter.deviantart.com/gallery/
50 elements.

Now, the main [profile page](http://inkveil-matter.deviantart.com/) says:
190 deviations.

A small discrepancy. 

But, thank god, there is [more](http://inkveil-matter.deviantart.com/stats/gallery/)

> InkVeil-Matter has 93,824 pageviews in total; their 35 journals and the 155 deviations in their gallery were viewed 733,645 times. [...]

155 + 35 = 190

Nice.

I have actually no idea what the Journal is, but I did a download with the gallery URL and got 155 Files.

That part seems to be working fine, so far..

**Comment by rautamiekka** [comment] 2017-04-13 15:30
To put it simply, journals (not just on DA, but at least FurAffinity and Inkbunny as well) are like Facebook wall posts, you can write whatever you can care to write. But the journals support HTML and CSS (paying users only).

**Comment by Wiiplay123** [comment] 2017-05-05 00:34
Being able to download literature for gallery would be nice, since some artists exclusively make literature and no images.

**Comment by rautamiekka** [comment] 2017-05-07 16:35
^ That belongs to a new issue.

**Comment by metaprime** [comment] 2017-05-09 10:14
@Wiiplay123 @rautamiekka Made a new issue: #525

**Comment by metaprime** [comment] 2017-05-24 17:13
Fixed in #516 (version 1.4.15+)

**Closed by metaprime** 2017-05-24 17:13 UTC
Labels: bug
