### ISSUE TITLE
Error: newsfilter.orghttp

### ISSUE THREAD

**Issue by Dr-Binder** [4pr0n/ripme#350] opened 2016-09-30 10:07 UTC
When trying to rip a newsfilter-gallery I always come along this error message. What can I do to avoid this?

Thanks in advance!

**Comment by metaprime** [comment] 2016-12-19 11:46
Marking as duplicate of #370 which has more information.

I'll try to put together a fix for this.

Closing this instance of this issue.

**Closed by metaprime** 2016-12-19 11:46 UTC
Labels: bug, duplicate
