### ISSUE TITLE
deviantart not working

### ISSUE THREAD

**Issue by MajorMilk90** [4pr0n/ripme#437] opened 2017-01-30 15:37 UTC
I have tried downloading user's albums but all that comes up is this. 
![da](https://cloud.githubusercontent.com/assets/25435738/22429277/b1cac4e8-e6cf-11e6-89b5-a1a2ca46239d.png)

**Comment by Phenrei** [comment] 2017-01-30 16:42
There were a collection of changes which broke things in multiple ways. The login has a new hidden token system, if not logged in pagination is broken (new autofill scroll system, requires account setting to revert), multiple elements had class name changes, etc. All is fixable, I got the core features working on my fork, and I'll try to clean it up into a pull request later.

**Comment by metaprime** [comment] 2017-02-01 00:51
Duplicate of #424

**Closed by metaprime** 2017-02-01 00:51 UTC

**Comment by ph0enixph0enix** [comment] 2017-03-22 14:10
@Phenrei: You got a fix for the DeviantArt ripper? I fixed the login localy at my pc but seems I can't get around the scroll type loading mechanism.

I changed the account settings of the accounts which I use for Ripme (slight modification of the src code) to use pagination but to no avail.

As you said, some class names and so on have changed...

If you got some kind of fix for that, could you please provide it or share your thoughts about it?

**Comment by metaprime** [comment] 2017-04-08 18:57
@ph0enixph0enix it's probably not the most productive to post on a duped issue. Please add to the discussion on #424 and see if there are any open PRs that might serve your purposes.
