### ISSUE TITLE
Re-Rip without trying to re-download everything.

### ISSUE THREAD

**Issue by tehloxely** [4pr0n/ripme#382] opened 2016-12-20 15:11 UTC
I would really like it to be possible for the app to re-download only NEW posts from your history. Would that be possible? Every time I click re-rip it tries to download everything from the past of something, as well as the new content.

**Comment by rautamiekka** [comment] 2016-12-20 17:25
I see your point, which'd be good. Although it doesn't take very long for RipMe to notice there are uploads it already has, it's waste of time and makes getting auto-banned more likely trying every link.

If it was up to me to implement, RipMe probly already makes a list of links it'll rip once it has scanned a page, change it to consult the list of already done links if that list ain't empty while adding the links-to-rip.

**Comment by metaprime** [comment] 2016-12-20 19:48
I believe this is a duplicate of #163 - let me know if that doesn't cover the scenarios you're thinking of.

**Closed by metaprime** 2016-12-20 19:48 UTC
Labels: duplicate, enhancement
