### ISSUE TITLE
HentaiFoundry 404

### ISSUE THREAD

**Issue by rawr123** [4pr0n/ripme#326] opened 2016-04-27 05:10 UTC
Downloading http://pictures.hentai-foundry.com//c/CupCake992/356050.jpg
Downloading http://pictures.hentai-foundry.com//c/CupCake992/355595.jpg
Downloading http://pictures.hentai-foundry.com//c/CupCake992/356050.jpg
Downloading http://pictures.hentai-foundry.com//c/CupCake992/355595.jpg
http://pictures.hentai-foundry.com//c/CupCake992/358223.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//c/CupCake992/358223.jpg
Downloading http://pictures.hentai-foundry.com//c/CupCake992/355594.jpg
http://pictures.hentai-foundry.com//c/CupCake992/355595.jpg : Non-retriable status code 404 while downloading http://pictures.hentai-foundry.com//c/CupCake992/355595.jpg
Downloading http://pictures.hentai-foundry.com//c/CupCake992/355343.jpg
http://pictures.hentai-foundry.com//c/CupCake992/356050.jpg : Non-retriable status code 404 while

Seems to be trying to putting .jpg in the url instead of the real file type which is .png which causes a 404. 

Seems to be similar to #157

**Comment by metaprime** [comment] 2016-12-19 12:26
Duplicate of #157

**Closed by metaprime** 2016-12-19 12:26 UTC
Labels: bug, duplicate
