### ISSUE TITLE
DeviantArt: Non-retriable status code 404 for certain images

### ISSUE THREAD

**Issue by HellcatAisha** [4pr0n/ripme#200] opened 2015-04-12 23:03 UTC
I've noticed that ripme fails to download certain images from DeviantArt, returning errors such as

```
Downloading http://t05.deviantart.net/Zzl79dW5tkQc-a9pgIdNRncm7a0=/filters:fixed_height(100,100):origin()/pre04/865d/th/pre/f/2015/101/2/9/9s_by_wlop-d8pa466.jpg
http://t05.deviantart.net/Zzl79dW5tkQc-a9pgIdNRncm7a0=/filters:fixed_height(100,100):origin()/pre04/865d/th/pre/f/2015/101/2/9/9s_by_wlop-d8pa466.jpg : Non-retriable status code 404 while downloading http://t05.deviantart.net/Zzl79dW5tkQc-a9pgIdNRncm7a0=/filters:fixed_height(100,100):origin()/pre04/865d/th/pre/f/2015/101/2/9/9s_by_wlop-d8pa466.jpg
```

As an example, the first 10 or so images of [this gallery](http://wlop.deviantart.com/gallery/?catpath=/) won't download, but the ones following will.

At a glance, I can't discern why some images fail to download and others don't. At first I thought it was related to the presence or absence of a "Download" button in the right-hand pane of an image page (e.g., [this image](http://wlop.deviantart.com/art/Light-and-Darkness-443767703?q=sort%3Atime%20gallery%3Awlop&qo=47)), but that does not appear to be the case, since the ripper is able to download [this image](http://wlop.deviantart.com/art/Dawn-516611942) just fine.

**Comment by ezsepnio** [comment] 2015-07-15 00:54
Hi guys, I am having the same 404 error.  

At times I get minimal 404 errors while on certain galleries I receive 404 errors on most of the images.

**Comment by metaprime** [comment] 2016-12-19 13:48
Duplicate of #337

**Closed** 2016-12-19 13:48 UTC
Labels: bug, duplicate
